create table MESSAGE(
	MID INT NOT NULL AUTO_INCREMENT, 
	UID varchar(255) NOT NULL,
	RID varchar(255) NOT NULL,
	TITLE varchar(255),
	SENDDATE DATETIME,
	CONTENT TEXT,
	RDCHECK INT default 0,
	primary key(MID, UID)
)default CHARSET=utf8;

ALTER TABLE MESSAGE ADD CONSTRAINT message_member_fk FOREIGN KEY(UID) REFERENCES MEMBER(ID) ON UPDATE CASCADE;
