create table BOARD(
	BID INT NOT NULL AUTO_INCREMENT, 
	ID varchar(255),
	TITLE varchar(255),
	REGDATE DATETIME,
	UPDATETIME DATETIME,
	IMAGE varchar(255),
	CONTENT TEXT,
	GOODHIT INT default 0,
	HIT INT default 0,
	FIRSTADD varchar(255),
	SECONDADD varchar(255),
	primary key(BID)
)default CHARSET=utf8;

ALTER TABLE BOARD ADD CONSTRAINT board_member_fk FOREIGN KEY(ID) REFERENCES MEMBER(ID) ON UPDATE CASCADE;

ALTER TABLE BOARD ADD COLUMN mbti varchar(4) AFTER ID;

ALTER TABLE BOARD DROP CONSTRAINT board_member_fk;

ALTER TABLE BOARD ADD CONSTRAINT board_member_fk FOREIGN KEY(ID) REFERENCES MEMBER(ID) ON UPDATE CASCADE ON DELETE CASCADE;